#!/bin/bash
# Setup External Storage in Nextcloud

echo "🔧 Configuring External Storage for Nextcloud"
echo "=============================================="
echo ""

# Enable External Storage app via occ command
echo "📦 Enabling External Storage app..."
docker exec -u www-data kekeli-nextcloud-app php occ app:enable files_external

echo ""
echo "✅ External Storage app enabled!"
echo ""
echo "📋 Next Steps - Configure via Web Interface:"
echo ""
echo "1. Access Nextcloud: http://10.182.80.100"
echo "2. Login with admin credentials"
echo "3. Click your profile icon (top right) → Apps"
echo "4. Go to 'Files' section on left"
echo "5. Find 'External storage support' - it should now be enabled"
echo ""
echo "6. Click profile icon → Settings (or Administration settings)"
echo "7. In the left menu, go to: Administration → External storage"
echo "8. Click 'Add storage' → 'Local'"
echo ""
echo "9. Configure the mount:"
echo "   - Folder name: External Drive (or whatever you want to call it)"
echo "   - Configuration: /external-data"
echo "   - Available for: (select users or groups who should have access)"
echo ""
echo "10. Click the checkmark to save"
echo ""
echo "📁 Your folders will then appear in Nextcloud Files!"
echo "   - BlackMythWukong"
echo "   - Fortnite"
echo "   - church files"
echo "   - admin"
echo "   - etc."
echo ""
echo "💡 Tip: You can also create subdirectories:"
echo "   - /external-data/church files for church content"
echo "   - /external-data/admin for admin files"
echo "   - etc."
